events {
    worker_connections 1024;
}

http {
    upstream fastapi_servers {
        server fastapi:8000;
        # Add more FastAPI servers here as needed
        # server fastapi2:8000;
        # server fastapi3:8000;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://fastapi_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
} 